export enum productActionTypes {
  GET_PRODUCT_BY_ID__START = 'GET_PRODUCT_BY_ID__START',
  GET_PRODUCT_BY_ID__SUCCESS = 'GET_PRODUCT_BY_ID__SUCCESS',
  GET_PRODUCT_BY_ID__FAILURE = 'GET_PRODUCT_BY_ID__FAILURE',
  
  REMOVE_PRODUCT_BY_ID__START = 'REMOVE_PRODUCT_BY_ID__START',
  REMOVE_PRODUCT_BY_ID__SUCCESS = 'REMOVE_PRODUCT_BY_ID__SUCCESS',
  REMOVE_PRODUCT_BY_ID__FAILURE = 'REMOVE_PRODUCT_BY_ID__FAILURE',
}
